### ISSUE TITLE
Customize Start Message

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#18]
When invites are started a message is sent to the guild, I am wondering if there is an option somewhere so that I can customize this message? Also it would be great if you could do this per raid team. This important now due to having 10 man and 25 man teams so it helps distinguish which raid team you are starting up.

**Comment by f90** [comment]
One option would be to include a custom message on a per-roster basis, there you get maximum flexibility and you can setup multiple rosters at the same time and then just invite them later without needing to modify the messages. But this has a number of complications:

- I need some way in the UI to show and make this message editable, and the settings menu isn't suited to that since one would expect these settings to be global. And the normal UI is already pretty full and doesn't offer space for this directly
- It complicates the data structure of a roster
- Need to think about what happens if you copy and send rosters - should the messages be copied over too? Is that desired?
- Deleting a roster and creating a new one means you lose the message you might want to reuse

Instead a good compromise would be to expose the guild message in the normal settings and have that be used for every roster. This is easy and safe to implement. And if you want to change from inviting a 25 to a 10man team, you can quickly edit the message manually. Or you can set up multiple messages and then quick-switch between them.

What do you think?

**Comment by f90** [comment]
We could also expose the guild end messages and other messages in the settings as well, if we are already doing this :)

**Comment by f90** [comment]
Implemented global settings for invite phase start and end guild notifications in 2.4.0
