### ISSUE TITLE
Add a setting to allow invites to work when alone

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#19]
[11:33] RaidInviteClassic: A codeword whisper by Somename-Herod was ignored because you were alone.

It would be great if I could use this as a general invite tool as well, not just when I click "start invites". Currently unless I am in a group and somebody whispers me the invite word then it is ignored with the error message above.

**Comment by f90** [comment]
I think what you need is already implemented. Uncheck "Only in group" option under Codewords->Restrictions. Then someone can whisper you and you start opening a raid from scratch as well.

Closing this issue, reopen if I misunderstood this problem.

**Comment by bagzli** [comment]
Ok, thanks I will test that. However I did notice a problem now when I have it set to not send initial invites and that option is checked. If I click start invites, the first person that send me xxx gets declined with the error from my previous message.

**Comment by f90** [comment]
OK that's a good point I haven't considered - when using the addon in "codeword-whisper-only" mode (not actively sending out invites), it doesn't make sense to block invites when you are still alone, since noone can actually use the whispers that way. The obvious solution is to disable that restriction, but that's a limiting workaround since you still might want to block invites when alone, but allow them once you're in the invite phase.

I think I will simply change the "Only in group" option to have an exception where it doesn't block a whisper if you're alone, but you are currently in an invite phase.

**Comment by bagzli** [comment]
why not make it a choice and let me choose if I want that on or off?

**Comment by f90** [comment]
For simplicity I thought not having an option is better (settings are already a bit cluttered by now). If I add that option, then one of the two possible settings would lead to the following:

You start an invite phase, meaning you WANT to get people into a group that you lead, but then block them ("Only in group" active) because you are currently alone, and then if you manually invite one person first it suddenly works again. 

I don't think this setting is useful in any scenario, do you think there is one? That's why I think forcing the only-in-group restriction to be inactive during invite phase makes sense.

**Comment by f90** [comment]
Released as explained above in v2.4.1
