### ISSUE TITLE
People on roster should be allowed to join via keyword

### ISSUE THREAD

**Issue by bagzli** [f90/RaidInviteClassic#24]
Currently I have the invite guild-mates only option on. But from time to time we pug. I feel that if I add somebody to the roster and I click Start Invites, then regardless of guild they should be allowed to join via the keyword. The auto inviter invites them at start, but if they are not online they should be allowed to join via keyword. Currently we get:

[19:10] To [Jonithian]: [RIC]: You are not a guild member. Only guild members are invited automatically.

**Comment by f90** [comment]
Nice suggestion, I agree that if your player is on the roster (your own decision), it does not make sense to deny them because they are not in the guild. Do you mind downloading the `dev` branch code and trying it out ingame? I changed it so that if you are on the roster, the guild check is not performed and you should be accepted! If you notify me that everything works as expected I will release it in the next version

**Comment by bagzli** [comment]
ok

**Comment by bagzli** [comment]
Tested today and it worked.

**Comment by f90** [comment]
Great! Thanks for your help!
